version: "3.9"
services:
  qqqm:
    build: .
    container_name: qqqm-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
